<template>
  <a-row :gutter="[24, 24]" :wrap="true">
    <BaseWidget
      :height="110"
      title="Visitor"
      :value="machineStore.totalMachine"
      :icon="SettingOutlined"
      description="Counted visitor listed on database"
    />
    <BaseWidget
      :height="110"
      title="Major"
      :value="machineStore.totalMachine"
      :icon="ExclamationCircleOutlined"
      description="Counted major listed on database"
    />
    <BaseWidget
      :height="110"
      title="Resume"
      description="The resume is generated by the Ollama AI module (Gemma3:270m) based on data stored in the database"
      :icon="AlignCenterOutlined"
    />
  </a-row>
</template>

<script setup>
import BaseWidget from '@/components/base/BaseWidget.vue'
import { useMachineStore } from '@/stores/machine'
import {
  SettingOutlined,
  ExclamationCircleOutlined,
  AlignCenterOutlined,
} from '@ant-design/icons-vue'
const machineStore = useMachineStore()
</script>

<style scoped></style>
